[gcp_service_account]
type = "service_account"
project_id = "massive-hub-454304-h3"
private_key_id = "0d1d6ec4bbd9672a7ce0509c4cb29ac29f4567bd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC19yMmk7WtdIrN
68Lluc027pYhJSgGZgPGpTs6Yv33ahzLUrqWuwVhrmGD/uARquGAHvW11MH4dmX3
9hJ0plNKJndD1QQLJUNGeP+DgNXCSPDpqd2bLhQjE6vVk642x0TwLyl6lr/4HZ9v
YTQJhg2xv0euVAUJ1OkY44EB/5oOjZbEecvpay7ks8o3RmPHGeofPhHB7jizwehR
3WNx5Vav1iT62FlDppPuZyaLlSSunoRjL61Up5WWg5zwcuUKVY9mTgEn3Uc9n7r0
i7GEwuTYOWQ5u7OMMbY12Za1cDKE7ep+Z1yEmPAF+pxQ+QI6j/b/19S/ddg7V9c6
keq+qzrHAgMBAAECggEABOxH07U5vEfjsgJBSK3OdR5FNUQXA4ZegAzLBBb5AAJ4
Q1w6bFw1nzJjgYqzd+B/YmUNolirOOmjpv/e5/Q29KclOuOC3hgxltMKaduVZGLm
aBJbW7JbtnHlzIAcNSt02CVZKrxsB9TURUqdzyDzuzqNlaVJWEa/82yyJNFMKF+G
V40cHkTT70oMQKaJYXXVnlznwYX6Yl08vbHFpN5M4Bq4QZEPghzUE+kPRDqIJ0Yn
Q66STbS7bur0h3dwdhRtaCpPaP5fYZXljX6euYyQxmlZt6eawl7xHOvKmzOqga/D
c9WlhNPrI075P7Ean2o3NORExfbIjPU0LMHluLargQKBgQD5ogCYEp2rG73N0/KA
jPg1r3eAy12sKlvFrnA0N3ps1EaOFMlv6FW6jNpJ8+vnLOwP3qFSTwnkLakQwhL5
V7SBW6WfMRwHGg67irTMZwtZFm+INw86RDwEO1dQ81Q64EbHPlAw5ZrS4Oa7v6og
C3CLyv4wB6LslZ1XhOG1F9hdMQKBgQC6m0uCguydQaXkDNWdnag/l8zEZdDwDbVF
SlrgQ6qJXvMkZAoPIY17SnoxCKymeNELVbQb4IYUrgsj1mbwQLBWVwJ2M3I6j+tL
PBzSTXwl84jFugWkdvTEyY7G4qlyWKsrgmLmpzeQVslzB44ALeKXkvyEUtHw/34x
9eFJy9g5dwKBgBGmrNgT6OYibgdRx0HjteFF6PNIbfUwgZC2xuRKT/PGBr8hJSUu
jnFEaGL2RmXwPTjaCxog0Jg7ykqPDnxnATJsYoehF1RBOW11X1dcqebAuV4uVntO
O9gowgHNUtVe6mJIO69ZbNsgX/BCmyrs5CZeUh7fS1vjMF7x3GvLpdbhAoGAHeZm
OfpKeYQcVacszz2EyPPEzq9VxDEeG4UnfIm7GJnLMciJyBTjO58aZyLxrxbqv/sy
icj3Evc0N8DR66sh1iPI9DGYGwQWeo6eO6BIxTf5cV02LD0XSTTWmM2WwwisHKOe
v0CJ6anOS40pVqQDi6/0oCs5EnmNuemg+JceBU8CgYEAnPNci6DhSS6QgOcLjt/u
r4TejlTERzFpqOSx/15GVKYGR4wgxx/c+lKEELSXPYSCkt/se1dunN+cv6Xw5re2
EFAEGN4Uwc+bxRsKkT5BZC0rvdZkdqXHVVOk2Xb9k2P6f2Ii95y7FNMJgsP0laO7
LBHNF30rZBk+MoKadoGPCI8=
-----END PRIVATE KEY-----"""
client_email = "laundry-service-account-830@massive-hub-454304-h3.iam.gserviceaccount.com"
client_id = "102160597981550964277"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/laundry-service-account-830@massive-hub-454304-h3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
